	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

	.align 2
Cry_Argomon_f::
	.incbin "sound/direct_sound_samples/cries/argomon_f.bin"

	.align 2
Cry_Bombmon::
	.incbin "sound/direct_sound_samples/cries/bombmon.bin"

	.align 2
Cry_Bommon::
	.incbin "sound/direct_sound_samples/cries/bommon.bin"

	.align 2
Cry_Botamon::
	.incbin "sound/direct_sound_samples/cries/botamon.bin"

	.align 2
Cry_Chibickmon::
	.incbin "sound/direct_sound_samples/cries/chibickmon.bin"

	.align 2
Cry_Chibomon::
	.incbin "sound/direct_sound_samples/cries/chibomon.bin"

	.align 2
Cry_Conomon::
	.incbin "sound/direct_sound_samples/cries/conomon.bin"

	.align 2
Cry_Cotsucomon::
	.incbin "sound/direct_sound_samples/cries/cotsucomon.bin"

	.align 2
Cry_curimon::
	.incbin "sound/direct_sound_samples/cries/curimon.bin"

	.align 2
Cry_Datirimon::
	.incbin "sound/direct_sound_samples/cries/datirimon.bin"

	.align 2
Cry_Dodomon::
	.incbin "sound/direct_sound_samples/cries/dodomon.bin"

	.align 2
Cry_Dokimon::
	.incbin "sound/direct_sound_samples/cries/dokimon.bin"

	.align 2
Cry_Fufumon::
	.incbin "sound/direct_sound_samples/cries/fufumon.bin"

	.align 2
Cry_Jyarimon::
	.incbin "sound/direct_sound_samples/cries/jyarimon.bin"

	.align 2
Cry_Keemon::
	.incbin "sound/direct_sound_samples/cries/keemon.bin"

	.align 2
Cry_Ketomon::
	.incbin "sound/direct_sound_samples/cries/ketomon.bin"

	.align 2
Cry_Kuramon::
	.incbin "sound/direct_sound_samples/cries/kuramon.bin"

	.align 2
Cry_Leafmon::
	.incbin "sound/direct_sound_samples/cries/leafmon.bin"

	.align 2
Cry_Choromon::
	.incbin "sound/direct_sound_samples/cries/choromon.bin"

	.align 2
Cry_Mokumon::
	.incbin "sound/direct_sound_samples/cries/mokumon.bin"

	.align 2
Cry_Nyokimon::
	.incbin "sound/direct_sound_samples/cries/nyokimon.bin"

	.align 2
Cry_Pabumon::
	.incbin "sound/direct_sound_samples/cries/pabumon.bin"

	.align 2
Cry_Pafumon::
	.incbin "sound/direct_sound_samples/cries/pafumon.bin"

	.align 2
Cry_Paomon::
	.incbin "sound/direct_sound_samples/cries/paomon.bin"

	.align 2
Cry_Petitmon::
	.incbin "sound/direct_sound_samples/cries/petitmon.bin"

	.align 2
Cry_Pichimon::
	.incbin "sound/direct_sound_samples/cries/pichimon.bin"

	.align 2
Cry_Popomon::
	.incbin "sound/direct_sound_samples/cries/popomon.bin"

	.align 2
Cry_Poyomon::
	.incbin "sound/direct_sound_samples/cries/poyomon.bin"

	.align 2
Cry_Punimon::
	.incbin "sound/direct_sound_samples/cries/punimon.bin"

	.align 2
Cry_Pupumon::
	.incbin "sound/direct_sound_samples/cries/pupumon.bin"

	.align 2
Cry_Pururumon::
	.incbin "sound/direct_sound_samples/cries/pururumon.bin"

	.align 2
Cry_Pusumon::
	.incbin "sound/direct_sound_samples/cries/pusumon.bin"

	.align 2
Cry_Puttimon::
	.incbin "sound/direct_sound_samples/cries/puttimon.bin"

	.align 2
Cry_Puwamon::
	.incbin "sound/direct_sound_samples/cries/puwamon.bin"

	.align 2
Cry_Puyomon::
	.incbin "sound/direct_sound_samples/cries/puyomon.bin"

	.align 2
Cry_Pyonmon::
	.incbin "sound/direct_sound_samples/cries/pyonmon.bin"

	.align 2
Cry_Relemon::
	.incbin "sound/direct_sound_samples/cries/relemon.bin"

	.align 2
Cry_Sakumon::
	.incbin "sound/direct_sound_samples/cries/sakumon.bin"

	.align 2
Cry_Sandmon::
	.incbin "sound/direct_sound_samples/cries/sandmon.bin"

	.align 2
Cry_Tsubumon::
	.incbin "sound/direct_sound_samples/cries/tsubumon.bin"

	.align 2
Cry_Icebotamon::
	.incbin "sound/direct_sound_samples/cries/icebotamon.bin"

	.align 2
Cry_Yuramon::
	.incbin "sound/direct_sound_samples/cries/yuramon.bin"

	.align 2
Cry_Zerimon::
	.incbin "sound/direct_sound_samples/cries/zerimon.bin"

	.align 2
Cry_Zurumon::
	.incbin "sound/direct_sound_samples/cries/zurumon.bin"

	.align 2
Cry_Arcadiamon_it::
	.incbin "sound/direct_sound_samples/cries/arcadiamon_it.bin"

	.align 2
Cry_Argomon_it::
	.incbin "sound/direct_sound_samples/cries/argomon_it.bin"

	.align 2
Cry_Babydmon::
	.incbin "sound/direct_sound_samples/cries/babydmon.bin"

	.align 2
Cry_Bibimon::
	.incbin "sound/direct_sound_samples/cries/bibimon.bin"

	.align 2
Cry_Bosamon::
	.incbin "sound/direct_sound_samples/cries/bosamon.bin"

	.align 2
Cry_Budmon::
	.incbin "sound/direct_sound_samples/cries/budmon.bin"

	.align 2
Cry_Bukamon::
	.incbin "sound/direct_sound_samples/cries/bukamon.bin"

	.align 2
Cry_Calumon::
	.incbin "sound/direct_sound_samples/cries/calumon.bin"

	.align 2
Cry_Chapmon::
	.incbin "sound/direct_sound_samples/cries/chapmon.bin"

	.align 2
Cry_Chicchimon::
	.incbin "sound/direct_sound_samples/cries/chicchimon.bin"

	.align 2
Cry_Demmeramon::
	.incbin "sound/direct_sound_samples/cries/demmeramon.bin"

	.align 2
Cry_Demiveemon::
	.incbin "sound/direct_sound_samples/cries/demiveemon.bin"

	.align 2
Cry_Dorimon::
	.incbin "sound/direct_sound_samples/cries/dorimon.bin"

	.align 2
Cry_Frimon::
	.incbin "sound/direct_sound_samples/cries/frimon.bin"

	.align 2
Cry_Gigimon::
	.incbin "sound/direct_sound_samples/cries/gigimon.bin"

	.align 2
Cry_Gummymon::
	.incbin "sound/direct_sound_samples/cries/gummymon.bin"

	.align 2
Cry_Gurimon::
	.incbin "sound/direct_sound_samples/cries/gurimon.bin"

	.align 2
Cry_Hiyarimon::
	.incbin "sound/direct_sound_samples/cries/hiyarimon.bin"

	.align 2
Cry_Hopmon::
	.incbin "sound/direct_sound_samples/cries/hopmon.bin"

	.align 2
Cry_Kakkinmon::
	.incbin "sound/direct_sound_samples/cries/kakkinmon.bin"

	.align 2
Cry_Kapurimon::
	.incbin "sound/direct_sound_samples/cries/kapurimon.bin"

	.align 2
Cry_Kokomon::
	.incbin "sound/direct_sound_samples/cries/kokomon.bin"

	.align 2
Cry_Koromon::
	.incbin "sound/direct_sound_samples/cries/koromon.bin"

	.align 2
Cry_Kozenimon::
	.incbin "sound/direct_sound_samples/cries/kozenimon.bin"

	.align 2
Cry_Kyaromon::
	.incbin "sound/direct_sound_samples/cries/kyaromon.bin"

	.align 2
Cry_Kyokyomon::
	.incbin "sound/direct_sound_samples/cries/kyokyomon.bin"

	.align 2
Cry_Kyupimon::
	.incbin "sound/direct_sound_samples/cries/kyupimon.bin"

	.align 2
Cry_Minomon::
	.incbin "sound/direct_sound_samples/cries/minomon.bin"

	.align 2
Cry_Missimon::
	.incbin "sound/direct_sound_samples/cries/missimon.bin"

	.align 2
Cry_Monimon::
	.incbin "sound/direct_sound_samples/cries/monimon.bin"

	.align 2
Cry_Moonmon::
	.incbin "sound/direct_sound_samples/cries/moonmon.bin"

	.align 2
Cry_Motimon::
	.incbin "sound/direct_sound_samples/cries/motimon.bin"

	.align 2
Cry_Negamon::
	.incbin "sound/direct_sound_samples/cries/negamon.bin"

	.align 2
Cry_Nyaromon::
	.incbin "sound/direct_sound_samples/cries/nyaromon.bin"

	.align 2
Cry_Pagumon::
	.incbin "sound/direct_sound_samples/cries/pagumon.bin"

	.align 2
Cry_Pickmon_silver::
	.incbin "sound/direct_sound_samples/cries/pickmon_silver.bin"

	.align 2
Cry_Pickmon_white::
	.incbin "sound/direct_sound_samples/cries/pickmon_white.bin"

	.align 2
Cry_Pickmon_red::
	.incbin "sound/direct_sound_samples/cries/pickmon_red.bin"

	.align 2
Cry_Pinamon::
	.incbin "sound/direct_sound_samples/cries/pinamon.bin"

	.align 2
Cry_Poromon::
	.incbin "sound/direct_sound_samples/cries/poromon.bin"

	.align 2
Cry_Puroromon::
	.incbin "sound/direct_sound_samples/cries/puroromon.bin"

	.align 2
Cry_Pusurimon::
	.incbin "sound/direct_sound_samples/cries/pusurimon.bin"

	.align 2
Cry_Puyoyomon::
	.incbin "sound/direct_sound_samples/cries/puyoyomon.bin"

	.align 2
Cry_Sakuttomon::
	.incbin "sound/direct_sound_samples/cries/sakuttomon.bin"

	.align 2
Cry_Sunmon::
	.incbin "sound/direct_sound_samples/cries/sunmon.bin"

	.align 2
Cry_Tanemon::
	.incbin "sound/direct_sound_samples/cries/tanemon.bin"

	.align 2
Cry_Tokomon::
	.incbin "sound/direct_sound_samples/cries/tokomon.bin"

	.align 2
Cry_Tokomon_x::
	.incbin "sound/direct_sound_samples/cries/tokomon_x.bin"

	.align 2
Cry_Torballmon::
	.incbin "sound/direct_sound_samples/cries/torballmon.bin"

	.align 2
Cry_Tsumemon::
	.incbin "sound/direct_sound_samples/cries/tsumemon.bin"

	.align 2
Cry_Tsunomon::
	.incbin "sound/direct_sound_samples/cries/tsunomon.bin"

	.align 2
Cry_Tumblemon::
	.incbin "sound/direct_sound_samples/cries/tumblemon.bin"

	.align 2
Cry_Upamon::
	.incbin "sound/direct_sound_samples/cries/upamon.bin"

	.align 2
Cry_Viximon::
	.incbin "sound/direct_sound_samples/cries/viximon.bin"

	.align 2
Cry_Wanyamon::
	.incbin "sound/direct_sound_samples/cries/wanyamon.bin"

	.align 2
Cry_Xiaomon::
	.incbin "sound/direct_sound_samples/cries/xiaomon.bin"

	.align 2
Cry_Yaamon::
	.incbin "sound/direct_sound_samples/cries/yaamon.bin"

	.align 2
Cry_Yokomon::
	.incbin "sound/direct_sound_samples/cries/yokomon.bin"

	.align 2
Cry_Agumon::
	.incbin "sound/direct_sound_samples/cries/agumon.bin"

	.align 2
Cry_Agumon_06::
	.incbin "sound/direct_sound_samples/cries/agumon_06.bin"

	.align 2
Cry_Agumon_expert::
	.incbin "sound/direct_sound_samples/cries/agumon_expert.bin"

	.align 2
Cry_Agumon_x::
	.incbin "sound/direct_sound_samples/cries/agumon_x.bin"

	.align 2
Cry_Angoramon::
	.incbin "sound/direct_sound_samples/cries/angoramon.bin"

	.align 2
Cry_Arcadiamon_rookie::
	.incbin "sound/direct_sound_samples/cries/arcadiamon_rookie.bin"

	.align 2
Cry_Argomon_rookie::
	.incbin "sound/direct_sound_samples/cries/argomon_rookie.bin"

	.align 2
Cry_Armadilmon::
	.incbin "sound/direct_sound_samples/cries/armadilmon.bin"

	.align 2
Cry_Aruraumon::
	.incbin "sound/direct_sound_samples/cries/aruraumon.bin"

	.align 2
Cry_Bakomon::
	.incbin "sound/direct_sound_samples/cries/bakomon.bin"

	.align 2
Cry_Bearmon::
	.incbin "sound/direct_sound_samples/cries/bearmon.bin"

	.align 2
Cry_Betamon::
	.incbin "sound/direct_sound_samples/cries/betamon.bin"

	.align 2
Cry_Betamon_x::
	.incbin "sound/direct_sound_samples/cries/betamon_x.bin"

	.align 2
Cry_Biyomon::
	.incbin "sound/direct_sound_samples/cries/biyomon.bin"

	.align 2
Cry_Blkagumon::
	.incbin "sound/direct_sound_samples/cries/blkagumon.bin"

	.align 2
Cry_Blkagumon_x::
	.incbin "sound/direct_sound_samples/cries/blkagumon_x.bin"

	.align 2
Cry_Blkgabumon::
	.incbin "sound/direct_sound_samples/cries/blkgabumon.bin"

	.align 2
Cry_Blkguilmon::
	.incbin "sound/direct_sound_samples/cries/blkguilmon.bin"

	.align 2
Cry_Bokomon::
	.incbin "sound/direct_sound_samples/cries/bokomon.bin"

	.align 2
Cry_Bulucomon::
	.incbin "sound/direct_sound_samples/cries/bulucomon.bin"

	.align 2
Cry_burgermon::
	.incbin "sound/direct_sound_samples/cries/burgermon.bin"

	.align 2
Cry_samuagumon::
	.incbin "sound/direct_sound_samples/cries/samuagumon.bin"

	.align 2
Cry_Candlemon::
	.incbin "sound/direct_sound_samples/cries/candlemon.bin"

	.align 2
Cry_Chikurimon::
	.incbin "sound/direct_sound_samples/cries/chikurimon.bin"

	.align 2
Cry_Tyutyumon::
	.incbin "sound/direct_sound_samples/cries/tyutyumon.bin"

	.align 2
Cry_Chuumon::
	.incbin "sound/direct_sound_samples/cries/chuumon.bin"

	.align 2
Cry_Hazyagumon::
	.incbin "sound/direct_sound_samples/cries/hazyagumon.bin"

	.align 2
Cry_Commdramon::
	.incbin "sound/direct_sound_samples/cries/commdramon.bin"

	.align 2
Cry_coronamon::
	.incbin "sound/direct_sound_samples/cries/coronamon.bin"

	.align 2
Cry_Crabmon::
	.incbin "sound/direct_sound_samples/cries/crabmon.bin"

	.align 2
Cry_Crabmon_x::
	.incbin "sound/direct_sound_samples/cries/crabmon_x.bin"

	.align 2
Cry_Cutemon::
	.incbin "sound/direct_sound_samples/cries/cutemon.bin"

	.align 2
Cry_Damemon::
	.incbin "sound/direct_sound_samples/cries/damemon.bin"

	.align 2
Cry_Demidevmon::
	.incbin "sound/direct_sound_samples/cries/demidevmon.bin"

	.align 2
Cry_Dokunemon::
	.incbin "sound/direct_sound_samples/cries/dokunemon.bin"

	.align 2
Cry_Dondokomon::
	.incbin "sound/direct_sound_samples/cries/dondokomon.bin"

	.align 2
Cry_Dorumon::
	.incbin "sound/direct_sound_samples/cries/dorumon.bin"

	.align 2
Cry_Dotagumon::
	.incbin "sound/direct_sound_samples/cries/dotagumon.bin"

	.align 2
Cry_Dotfalcmon::
	.incbin "sound/direct_sound_samples/cries/dotfalcmon.bin"

	.align 2
Cry_Dracmon::
	.incbin "sound/direct_sound_samples/cries/dracmon.bin"

	.align 2
Cry_Dracomon::
	.incbin "sound/direct_sound_samples/cries/dracomon.bin"

	.align 2
Cry_Dracomon_x::
	.incbin "sound/direct_sound_samples/cries/dracomon_x.bin"

	.align 2
Cry_Ebiburgmon::
	.incbin "sound/direct_sound_samples/cries/ebiburgmon.bin"

	.align 2
Cry_Ekakimon::
	.incbin "sound/direct_sound_samples/cries/ekakimon.bin"

	.align 2
Cry_Elecmon::
	.incbin "sound/direct_sound_samples/cries/elecmon.bin"

	.align 2
Cry_Elecmon_violet::
	.incbin "sound/direct_sound_samples/cries/elecmon_violet.bin"

	.align 2
Cry_Espimon::
	.incbin "sound/direct_sound_samples/cries/espimon.bin"

	.align 2
Cry_Agumon_fake_expert::
	.incbin "sound/direct_sound_samples/cries/agumon_fake_expert.bin"

	.align 2
Cry_Falcomon::
	.incbin "sound/direct_sound_samples/cries/falcomon.bin"

	.align 2
Cry_Falcomon_06::
	.incbin "sound/direct_sound_samples/cries/falcomon_06.bin"

	.align 2
Cry_Fanbeemon::
	.incbin "sound/direct_sound_samples/cries/fanbeemon.bin"

	.align 2
Cry_Flamemon::
	.incbin "sound/direct_sound_samples/cries/flamemon.bin"

	.align 2
Cry_Floramon::
	.incbin "sound/direct_sound_samples/cries/floramon.bin"

	.align 2
Cry_Gabumon::
	.incbin "sound/direct_sound_samples/cries/gabumon.bin"

	.align 2
Cry_Gabumon_x::
	.incbin "sound/direct_sound_samples/cries/gabumon_x.bin"

	.align 2
Cry_Gammamon::
	.incbin "sound/direct_sound_samples/cries/gammamon.bin"

	.align 2
Cry_Gaomon::
	.incbin "sound/direct_sound_samples/cries/gaomon.bin"

	.align 2
Cry_Gaossmon::
	.incbin "sound/direct_sound_samples/cries/gaossmon.bin"

	.align 2
Cry_Gazimon::
	.incbin "sound/direct_sound_samples/cries/gazimon.bin"

	.align 2
Cry_Gazimon_x::
	.incbin "sound/direct_sound_samples/cries/gazimon_x.bin"

	.align 2
Cry_Ghostmon::
	.incbin "sound/direct_sound_samples/cries/ghostmon.bin"

	.align 2
Cry_Gizamon::
	.incbin "sound/direct_sound_samples/cries/gizamon.bin"

	.align 2
Cry_Gizumon::
	.incbin "sound/direct_sound_samples/cries/gizumon.bin"

	.align 2
Cry_Goblimon::
	.incbin "sound/direct_sound_samples/cries/goblimon.bin"

	.align 2
Cry_Gomamon::
	.incbin "sound/direct_sound_samples/cries/gomamon.bin"

	.align 2
Cry_Gomamon_x::
	.incbin "sound/direct_sound_samples/cries/gomamon_x.bin"

	.align 2
Cry_Gotsumon::
	.incbin "sound/direct_sound_samples/cries/gotsumon.bin"

	.align 2
Cry_Gotsumon_x::
	.incbin "sound/direct_sound_samples/cries/gotsumon_x.bin"

	.align 2
Cry_Guilmon::
	.incbin "sound/direct_sound_samples/cries/guilmon.bin"

	.align 2
Cry_Guilmon_x::
	.incbin "sound/direct_sound_samples/cries/guilmon_x.bin"

	.align 2
Cry_Gumdramon::
	.incbin "sound/direct_sound_samples/cries/gumdramon.bin"

	.align 2
Cry_Hackmon::
	.incbin "sound/direct_sound_samples/cries/hackmon.bin"

	.align 2
Cry_Hagurumon::
	.incbin "sound/direct_sound_samples/cries/hagurumon.bin"

	.align 2
Cry_Hagurumon_x::
	.incbin "sound/direct_sound_samples/cries/hagurumon_x.bin"

	.align 2
Cry_Hawkmon::
	.incbin "sound/direct_sound_samples/cries/hawkmon.bin"

	.align 2
Cry_Herissmon::
	.incbin "sound/direct_sound_samples/cries/herissmon.bin"

	.align 2
Cry_Hyokomon::
	.incbin "sound/direct_sound_samples/cries/hyokomon.bin"

	.align 2
Cry_Ignitemon::
	.incbin "sound/direct_sound_samples/cries/ignitemon.bin"

	.align 2
Cry_Impmon::
	.incbin "sound/direct_sound_samples/cries/impmon.bin"

	.align 2
Cry_Impmon_x::
	.incbin "sound/direct_sound_samples/cries/impmon_x.bin"

	.align 2
Cry_Jazamon::
	.incbin "sound/direct_sound_samples/cries/jazamon.bin"

	.align 2
Cry_Jellymon::
	.incbin "sound/direct_sound_samples/cries/jellymon.bin"

	.align 2
Cry_Junkmon::
	.incbin "sound/direct_sound_samples/cries/junkmon.bin"

	.align 2
Cry_Kamemon::
	.incbin "sound/direct_sound_samples/cries/kamemon.bin"

	.align 2
Cry_Keramon::
	.incbin "sound/direct_sound_samples/cries/keramon.bin"

	.align 2
Cry_Keramon_x::
	.incbin "sound/direct_sound_samples/cries/keramon_x.bin"

	.align 2
Cry_Kodokgumon::
	.incbin "sound/direct_sound_samples/cries/kodokgumon.bin"

	.align 2
Cry_Kokabuimon::
	.incbin "sound/direct_sound_samples/cries/kokabuimon.bin"

	.align 2
Cry_Kokuwamon::
	.incbin "sound/direct_sound_samples/cries/kokuwamon.bin"

	.align 2
Cry_Kokuwamon_x::
	.incbin "sound/direct_sound_samples/cries/kokuwamon_x.bin"

	.align 2
Cry_Kotemon::
	.incbin "sound/direct_sound_samples/cries/kotemon.bin"

	.align 2
Cry_Kudamon::
	.incbin "sound/direct_sound_samples/cries/kudamon.bin"

	.align 2
Cry_Kudamon_06::
	.incbin "sound/direct_sound_samples/cries/kudamon_06.bin"

	.align 2
Cry_Kunemon::
	.incbin "sound/direct_sound_samples/cries/kunemon.bin"

	.align 2
Cry_Labramon::
	.incbin "sound/direct_sound_samples/cries/labramon.bin"

	.align 2
Cry_Lalamon::
	.incbin "sound/direct_sound_samples/cries/lalamon.bin"

	.align 2
Cry_Liollmon::
	.incbin "sound/direct_sound_samples/cries/liollmon.bin"

	.align 2
Cry_Loogamon::
	.incbin "sound/direct_sound_samples/cries/loogamon.bin"

	.align 2
Cry_Lopmon::
	.incbin "sound/direct_sound_samples/cries/lopmon.bin"

	.align 2
Cry_Lopmon_x::
	.incbin "sound/direct_sound_samples/cries/lopmon_x.bin"

	.align 2
Cry_Lucemon::
	.incbin "sound/direct_sound_samples/cries/lucemon.bin"

	.align 2
Cry_Ludomon::
	.incbin "sound/direct_sound_samples/cries/ludomon.bin"

	.align 2
Cry_Lunamon::
	.incbin "sound/direct_sound_samples/cries/lunamon.bin"

	.align 2
Cry_Luxmon::
	.incbin "sound/direct_sound_samples/cries/luxmon.bin"

	.align 2
Cry_Metabee::
	.incbin "sound/direct_sound_samples/cries/metabee.bin"

	.align 2
Cry_Kodekacmon::
	.incbin "sound/direct_sound_samples/cries/kodekacmon.bin"

	.align 2
Cry_Modbetamon::
	.incbin "sound/direct_sound_samples/cries/modbetamon.bin"

	.align 2
Cry_Monitamon::
	.incbin "sound/direct_sound_samples/cries/monitamon.bin"

	.align 2
Cry_Monmon::
	.incbin "sound/direct_sound_samples/cries/monmon.bin"

	.align 2
Cry_Monodramon::
	.incbin "sound/direct_sound_samples/cries/monodramon.bin"

	.align 2
Cry_Morphomon::
	.incbin "sound/direct_sound_samples/cries/morphomon.bin"

	.align 2
Cry_Muchomon::
	.incbin "sound/direct_sound_samples/cries/muchomon.bin"

	.align 2
Cry_Mushroomon::
	.incbin "sound/direct_sound_samples/cries/mushroomon.bin"

	.align 2
Cry_Neemon::
	.incbin "sound/direct_sound_samples/cries/neemon.bin"

	.align 2
Cry_Otamamon::
	.incbin "sound/direct_sound_samples/cries/otamamon.bin"

	.align 2
Cry_Otamamon_red::
	.incbin "sound/direct_sound_samples/cries/otamamon_red.bin"

	.align 2
Cry_Otamamon_x::
	.incbin "sound/direct_sound_samples/cries/otamamon_x.bin"

	.align 2
Cry_Palmon::
	.incbin "sound/direct_sound_samples/cries/palmon.bin"

	.align 2
Cry_Palmon_x::
	.incbin "sound/direct_sound_samples/cries/palmon_x.bin"

	.align 2
Cry_Patamon::
	.incbin "sound/direct_sound_samples/cries/patamon.bin"

	.align 2
Cry_Pawnmon::
	.incbin "sound/direct_sound_samples/cries/pawnmon.bin"

	.align 2
Cry_Pawnmon_white::
	.incbin "sound/direct_sound_samples/cries/pawnmon_white.bin"

	.align 2
Cry_Penguinmon::
	.incbin "sound/direct_sound_samples/cries/penguinmon.bin"

	.align 2
Cry_Petitmamon::
	.incbin "sound/direct_sound_samples/cries/petitmamon.bin"

	.align 2
Cry_Phascomon::
	.incbin "sound/direct_sound_samples/cries/phascomon.bin"

	.align 2
Cry_Pillomon::
	.incbin "sound/direct_sound_samples/cries/pillomon.bin"

	.align 2
Cry_Pomumon::
	.incbin "sound/direct_sound_samples/cries/pomumon.bin"

	.align 2
Cry_Psychemon::
	.incbin "sound/direct_sound_samples/cries/psychemon.bin"

	.align 2
Cry_Pulsemon::
	.incbin "sound/direct_sound_samples/cries/pulsemon.bin"

	.align 2
Cry_Renamon::
	.incbin "sound/direct_sound_samples/cries/renamon.bin"

	.align 2
Cry_Renamon_x::
	.incbin "sound/direct_sound_samples/cries/renamon_x.bin"

	.align 2
Cry_Rokusho::
	.incbin "sound/direct_sound_samples/cries/rokusho.bin"

	.align 2
Cry_Ryudamon::
	.incbin "sound/direct_sound_samples/cries/ryudamon.bin"

	.align 2
Cry_Salamon::
	.incbin "sound/direct_sound_samples/cries/salamon.bin"

	.align 2
Cry_Salamon_x::
	.incbin "sound/direct_sound_samples/cries/salamon_x.bin"

	.align 2
Cry_Sangomon::
	.incbin "sound/direct_sound_samples/cries/sangomon.bin"

	.align 2
Cry_santaagumon::
	.incbin "sound/direct_sound_samples/cries/santaagumon.bin"

	.align 2
Cry_Blktoyagumon::
	.incbin "sound/direct_sound_samples/cries/blktoyagumon.bin"

	.align 2
Cry_Shamanmon::
	.incbin "sound/direct_sound_samples/cries/shamanmon.bin"

	.align 2
Cry_Shoutmon::
	.incbin "sound/direct_sound_samples/cries/shoutmon.bin"

	.align 2
Cry_Yukiagumon::
	.incbin "sound/direct_sound_samples/cries/yukiagumon.bin"

	.align 2
Cry_Yukiagumon_06::
	.incbin "sound/direct_sound_samples/cries/yukiagumon_06.bin"

	.align 2
Cry_Icegobimon::
	.incbin "sound/direct_sound_samples/cries/icegobimon.bin"

	.align 2
Cry_Solarmon::
	.incbin "sound/direct_sound_samples/cries/solarmon.bin"

	.align 2
Cry_Sounbrdmon::
	.incbin "sound/direct_sound_samples/cries/sounbrdmon.bin"

	.align 2
Cry_Spadamon::
	.incbin "sound/direct_sound_samples/cries/spadamon.bin"

	.align 2
Cry_Sparrowmon::
	.incbin "sound/direct_sound_samples/cries/sparrowmon.bin"

	.align 2
Cry_Starmon_2010::
	.incbin "sound/direct_sound_samples/cries/starmon_2010.bin"

	.align 2
Cry_Strabimon::
	.incbin "sound/direct_sound_samples/cries/strabimon.bin"

	.align 2
Cry_Kecleon::
	.incbin "sound/direct_sound_samples/cries/kecleon.bin"

	.align 2
Cry_Roselia::
	.incbin "sound/direct_sound_samples/cries/roselia.bin"

	.align 2
Cry_Torkoal::
	.incbin "sound/direct_sound_samples/cries/torkoal.bin"

	.align 2
Cry_Electrike::
	.incbin "sound/direct_sound_samples/cries/electrike.bin"

	.align 2
Cry_Manectric::
	.incbin "sound/direct_sound_samples/cries/manectric.bin"

	.align 2
Cry_Duskull::
	.incbin "sound/direct_sound_samples/cries/duskull.bin"

	.align 2
Cry_Latias::
	.incbin "sound/direct_sound_samples/cries/latias.bin"

	.align 2
Cry_Wynaut::
	.incbin "sound/direct_sound_samples/cries/wynaut.bin"

	.align 2
Cry_Seviper::
	.incbin "sound/direct_sound_samples/cries/seviper.bin"

	.align 2
Cry_Sharpedo::
	.incbin "sound/direct_sound_samples/cries/sharpedo.bin"

	.align 2
Cry_Zangoose::
	.incbin "sound/direct_sound_samples/cries/zangoose.bin"

	.align 2
Cry_Azurill::
	.incbin "sound/direct_sound_samples/cries/azurill.bin"

	.align 2
Cry_Swablu::
	.incbin "sound/direct_sound_samples/cries/swablu.bin"

	.align 2
Cry_Altaria::
	.incbin "sound/direct_sound_samples/cries/altaria.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cries/unused_265.bin"

	.align 2
Cry_Allomon_x::
	.incbin "sound/direct_sound_samples/cries/allomon_x.bin"

	.align 2
Cry_Swellow::
	.incbin "sound/direct_sound_samples/cries/swellow.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cries/unused_268.bin"

	.align 2
Cry_Spinda::
	.incbin "sound/direct_sound_samples/cries/spinda.bin"

	.align 2
Cry_Syakomon_x::
	.incbin "sound/direct_sound_samples/cries/syakomon_x.bin"

	.align 2
Cry_Tapirmon::
	.incbin "sound/direct_sound_samples/cries/tapirmon.bin"

	.align 2
Cry_Tentomon::
	.incbin "sound/direct_sound_samples/cries/tentomon.bin"

	.align 2
Cry_Sunarzamon::
	.incbin "sound/direct_sound_samples/cries/sunarzamon.bin"

	.align 2
Cry_Swimmon::
	.incbin "sound/direct_sound_samples/cries/swimmon.bin"

	.align 2
Cry_Syakomon::
	.incbin "sound/direct_sound_samples/cries/syakomon.bin"

	.align 2
Cry_Terriermon::
	.incbin "sound/direct_sound_samples/cries/terriermon.bin"

	.align 2
Cry_Terriermon_assistant::
	.incbin "sound/direct_sound_samples/cries/terriermon_assistant.bin"

	.align 2
Cry_Terriermon_x::
	.incbin "sound/direct_sound_samples/cries/terriermon_x.bin"

	.align 2
Cry_Ankylomon::
	.incbin "sound/direct_sound_samples/cries/ankylomon.bin"

	.align 2
Cry_Angemon::
	.incbin "sound/direct_sound_samples/cries/angemon.bin"

	.align 2
Cry_Banette::
	.incbin "sound/direct_sound_samples/cries/banette.bin"

	.align 2
Cry_Shuppet::
	.incbin "sound/direct_sound_samples/cries/shuppet.bin"

	.align 2
Cry_Zubamon::
	.incbin "sound/direct_sound_samples/cries/zubamon.bin"

	.align 2
Cry_Aegiomon::
	.incbin "sound/direct_sound_samples/cries/aegiomon.bin"

	.align 2
Cry_Agunimon::
	.incbin "sound/direct_sound_samples/cries/agunimon.bin"

	.align 2
Cry_Airdramon::
	.incbin "sound/direct_sound_samples/cries/airdramon.bin"

	.align 2
Cry_Akatorimon::
	.incbin "sound/direct_sound_samples/cries/akatorimon.bin"

	.align 2
Cry_Allomon::
	.incbin "sound/direct_sound_samples/cries/allomon.bin"

	.align 2
Cry_Carvanha::
	.incbin "sound/direct_sound_samples/cries/carvanha.bin"

	.align 2
Cry_Veemon::
	.incbin "sound/direct_sound_samples/cries/veemon.bin"

	.align 2
Cry_Vemmon::
	.incbin "sound/direct_sound_samples/cries/vemmon.bin"

	.align 2
Cry_Vorvomon::
	.incbin "sound/direct_sound_samples/cries/vorvomon.bin"

	.align 2
Cry_Wormmon::
	.incbin "sound/direct_sound_samples/cries/wormmon.bin"

	.align 2
Cry_Zenimon::
	.incbin "sound/direct_sound_samples/cries/zenimon.bin"

	.align 2
Cry_Apemon::
	.incbin "sound/direct_sound_samples/cries/apemon.bin"

	.align 2
Cry_Aquilamon::
	.incbin "sound/direct_sound_samples/cries/aquilamon.bin"

	.align 2
Cry_Arcadiamon_champion::
	.incbin "sound/direct_sound_samples/cries/arcadiamon_champion.bin"

	.align 2
Cry_Slakoth::
	.incbin "sound/direct_sound_samples/cries/slakoth.bin"

	.align 2
Cry_Vigoroth::
	.incbin "sound/direct_sound_samples/cries/vigoroth.bin"

	.align 2
Cry_Slaking::
	.incbin "sound/direct_sound_samples/cries/slaking.bin"

	.align 2
Cry_Nincada::
	.incbin "sound/direct_sound_samples/cries/nincada.bin"

	.align 2
Cry_Ninjask::
	.incbin "sound/direct_sound_samples/cries/ninjask.bin"

	.align 2
Cry_Shedinja::
	.incbin "sound/direct_sound_samples/cries/shedinja.bin"

	.align 2
Cry_Makuhita::
	.incbin "sound/direct_sound_samples/cries/makuhita.bin"

	.align 2
Cry_Hariyama::
	.incbin "sound/direct_sound_samples/cries/hariyama.bin"

	.align 2
Cry_Nosepass::
	.incbin "sound/direct_sound_samples/cries/nosepass.bin"

	.align 2
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cries/glalie.bin"

	.align 2
Cry_Plusle::
	.incbin "sound/direct_sound_samples/cries/plusle.bin"

	.align 2
Cry_Minun::
	.incbin "sound/direct_sound_samples/cries/minun.bin"

	.align 2
Cry_Surskit::
	.incbin "sound/direct_sound_samples/cries/surskit.bin"

	.align 2
Cry_Masquerain::
	.incbin "sound/direct_sound_samples/cries/masquerain.bin"

	.align 2
Cry_Skitty::
	.incbin "sound/direct_sound_samples/cries/skitty.bin"

	.align 2
Cry_Delcatty::
	.incbin "sound/direct_sound_samples/cries/delcatty.bin"

	.align 2
Cry_Gulpin::
	.incbin "sound/direct_sound_samples/cries/gulpin.bin"

	.align 2
Cry_Swalot::
	.incbin "sound/direct_sound_samples/cries/swalot.bin"

	.align 2
Cry_Numel::
	.incbin "sound/direct_sound_samples/cries/numel.bin"

	.align 2
Cry_Camerupt::
	.incbin "sound/direct_sound_samples/cries/camerupt.bin"

	.align 2
Cry_Barboach::
	.incbin "sound/direct_sound_samples/cries/barboach.bin"

	.align 2
Cry_Whiscash::
	.incbin "sound/direct_sound_samples/cries/whiscash.bin"

	.align 2
Cry_Corphish::
	.incbin "sound/direct_sound_samples/cries/corphish.bin"

	.align 2
Cry_Crawdaunt::
	.incbin "sound/direct_sound_samples/cries/crawdaunt.bin"

	.align 2
Cry_Spoink::
	.incbin "sound/direct_sound_samples/cries/spoink.bin"

	.align 2
Cry_Grumpig::
	.incbin "sound/direct_sound_samples/cries/grumpig.bin"

	.align 2
Cry_Trapinch::
	.incbin "sound/direct_sound_samples/cries/trapinch.bin"

	.align 2
Cry_Vibrava::
	.incbin "sound/direct_sound_samples/cries/vibrava.bin"

	.align 2
Cry_Flygon::
	.incbin "sound/direct_sound_samples/cries/flygon.bin"

	.align 2
Cry_Cacnea::
	.incbin "sound/direct_sound_samples/cries/cacnea.bin"

	.align 2
Cry_Cacturne::
	.incbin "sound/direct_sound_samples/cries/cacturne.bin"

	.align 2
Cry_Baltoy::
	.incbin "sound/direct_sound_samples/cries/baltoy.bin"

	.align 2
Cry_Claydol::
	.incbin "sound/direct_sound_samples/cries/claydol.bin"

	.align 2
Cry_Lunatone::
	.incbin "sound/direct_sound_samples/cries/lunatone.bin"

	.align 2
Cry_Solrock::
	.incbin "sound/direct_sound_samples/cries/solrock.bin"

	.align 2
Cry_Feebas::
	.incbin "sound/direct_sound_samples/cries/feebas.bin"

	.align 2
Cry_Milotic::
	.incbin "sound/direct_sound_samples/cries/milotic.bin"

	.align 2
Cry_Absol::
	.incbin "sound/direct_sound_samples/cries/absol.bin"

	.align 2
Cry_Meditite::
	.incbin "sound/direct_sound_samples/cries/meditite.bin"

	.align 2
Cry_Medicham::
	.incbin "sound/direct_sound_samples/cries/medicham.bin"

	.align 2
Cry_Spheal::
	.incbin "sound/direct_sound_samples/cries/spheal.bin"

	.align 2
Cry_Sealeo::
	.incbin "sound/direct_sound_samples/cries/sealeo.bin"

	.align 2
Cry_Walrein::
	.incbin "sound/direct_sound_samples/cries/walrein.bin"

	.align 2
Cry_Clamperl::
	.incbin "sound/direct_sound_samples/cries/clamperl.bin"

	.align 2
Cry_Huntail::
	.incbin "sound/direct_sound_samples/cries/huntail.bin"

	.align 2
Cry_Gorebyss::
	.incbin "sound/direct_sound_samples/cries/gorebyss.bin"

	.align 2
Cry_Lileep::
	.incbin "sound/direct_sound_samples/cries/lileep.bin"

	.align 2
Cry_Cradily::
	.incbin "sound/direct_sound_samples/cries/cradily.bin"

	.align 2
Cry_Anorith::
	.incbin "sound/direct_sound_samples/cries/anorith.bin"

	.align 2
Cry_Armaldo::
	.incbin "sound/direct_sound_samples/cries/armaldo.bin"

	.align 2
Cry_Beldum::
	.incbin "sound/direct_sound_samples/cries/beldum.bin"

	.align 2
Cry_Metang::
	.incbin "sound/direct_sound_samples/cries/metang.bin"

	.align 2
Cry_Gaogamon::
	.incbin "sound/direct_sound_samples/cries/gaogamon.bin"

	.align 2
Cry_Bagon::
	.incbin "sound/direct_sound_samples/cries/bagon.bin"

	.align 2
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cries/shelgon.bin"

	.align 2
Cry_Regirock::
	.incbin "sound/direct_sound_samples/cries/regirock.bin"

	.align 2
Cry_Regice::
	.incbin "sound/direct_sound_samples/cries/regice.bin"

	.align 2
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cries/registeel.bin"

	.align 2
Cry_Castform::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Volbeat::
	.incbin "sound/direct_sound_samples/cries/volbeat.bin"

	.align 2
Cry_Illumise::
	.incbin "sound/direct_sound_samples/cries/illumise.bin"

	.align 2
Cry_Tinkermon::
	.incbin "sound/direct_sound_samples/cries/tinkermon.bin"

	.align 2
Cry_Tinpet::
	.incbin "sound/direct_sound_samples/cries/tinpet.bin"

	.align 2
Cry_Dusclops::
	.incbin "sound/direct_sound_samples/cries/dusclops.bin"

	.align 2
Cry_Sableye::
	.incbin "sound/direct_sound_samples/cries/sableye.bin"

	.align 2
Cry_Mawile::
	.incbin "sound/direct_sound_samples/cries/mawile.bin"

	.align 2
Cry_Aron::
	.incbin "sound/direct_sound_samples/cries/aron.bin"

	.align 2
Cry_Lairon::
	.incbin "sound/direct_sound_samples/cries/lairon.bin"

	.align 2
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cries/aggron.bin"

	.align 2
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Luvdisc::
	.incbin "sound/direct_sound_samples/cries/luvdisc.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cries/groudon.bin"

	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cries/kyogre.bin"

	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/rayquaza.bin"

	.align 2
Cry_Salamence::
	.incbin "sound/direct_sound_samples/cries/salamence.bin"

	.align 2
Cry_Breloom::
	.incbin "sound/direct_sound_samples/cries/breloom.bin"

	.align 2
Cry_Shroomish::
	.incbin "sound/direct_sound_samples/cries/shroomish.bin"

	.align 2
Cry_Tsukaimon::
	.incbin "sound/direct_sound_samples/cries/tsukaimon.bin"

	.align 2
Cry_Tropius::
	.incbin "sound/direct_sound_samples/cries/tropius.bin"

	.align 2
Cry_Wailmer::
	.incbin "sound/direct_sound_samples/cries/wailmer.bin"

	.align 2
Cry_Toyagumon::
	.incbin "sound/direct_sound_samples/cries/toyagumon.bin"

	.align 2
Cry_Exploud::
	.incbin "sound/direct_sound_samples/cries/exploud.bin"

	.align 2
Cry_Loudred::
	.incbin "sound/direct_sound_samples/cries/loudred.bin"

	.align 2
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cries/wailord.bin"

	.align 2
Cry_Whismur::
	.incbin "sound/direct_sound_samples/cries/whismur.bin"

	.align 2
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cries/snorunt.bin"

	.align 2
Cry_Latios::
	.incbin "sound/direct_sound_samples/cries/latios.bin"

	.align 2
Cry_Jirachi::
	.incbin "sound/direct_sound_samples/cries/jirachi.bin"

	.align 2
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cries/deoxys.bin"

	.align 2
Cry_Chimecho::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_Phoneme_1::
	.incbin "sound/direct_sound_samples/phonemes/01.bin"

	.align 2
DirectSoundWaveData_Phoneme_2::
	.incbin "sound/direct_sound_samples/phonemes/02.bin"

	.align 2
DirectSoundWaveData_Phoneme_3::
	.incbin "sound/direct_sound_samples/phonemes/03.bin"

	.align 2
DirectSoundWaveData_Phoneme_4::
	.incbin "sound/direct_sound_samples/phonemes/04.bin"

	.align 2
DirectSoundWaveData_Phoneme_5::
	.incbin "sound/direct_sound_samples/phonemes/05.bin"

	.align 2
DirectSoundWaveData_Phoneme_6::
	.incbin "sound/direct_sound_samples/phonemes/06.bin"

	.align 2
DirectSoundWaveData_Phoneme_7::
	.incbin "sound/direct_sound_samples/phonemes/07.bin"

	.align 2
DirectSoundWaveData_Phoneme_8::
	.incbin "sound/direct_sound_samples/phonemes/08.bin"

	.align 2
DirectSoundWaveData_Phoneme_9::
	.incbin "sound/direct_sound_samples/phonemes/09.bin"

	.align 2
DirectSoundWaveData_Phoneme_10::
	.incbin "sound/direct_sound_samples/phonemes/10.bin"

	.align 2
DirectSoundWaveData_Phoneme_11::
	.incbin "sound/direct_sound_samples/phonemes/11.bin"

	.align 2
DirectSoundWaveData_Phoneme_12::
	.incbin "sound/direct_sound_samples/phonemes/12.bin"

	.align 2
DirectSoundWaveData_Phoneme_13::
	.incbin "sound/direct_sound_samples/phonemes/13.bin"

	.align 2
DirectSoundWaveData_Phoneme_14::
	.incbin "sound/direct_sound_samples/phonemes/14.bin"

	.align 2
DirectSoundWaveData_Phoneme_15::
	.incbin "sound/direct_sound_samples/phonemes/15.bin"

	.align 2
DirectSoundWaveData_Phoneme_16::
	.incbin "sound/direct_sound_samples/phonemes/16.bin"

	.align 2
DirectSoundWaveData_Phoneme_17::
	.incbin "sound/direct_sound_samples/phonemes/17.bin"

	.align 2
DirectSoundWaveData_Phoneme_18::
	.incbin "sound/direct_sound_samples/phonemes/18.bin"

	.align 2
DirectSoundWaveData_Phoneme_19::
	.incbin "sound/direct_sound_samples/phonemes/19.bin"

	.align 2
DirectSoundWaveData_Phoneme_20::
	.incbin "sound/direct_sound_samples/phonemes/20.bin"

	.align 2
DirectSoundWaveData_Phoneme_21::
	.incbin "sound/direct_sound_samples/phonemes/21.bin"

	.align 2
DirectSoundWaveData_Phoneme_22::
	.incbin "sound/direct_sound_samples/phonemes/22.bin"

	.align 2
DirectSoundWaveData_Phoneme_23::
	.incbin "sound/direct_sound_samples/phonemes/23.bin"

	.align 2
DirectSoundWaveData_Phoneme_24::
	.incbin "sound/direct_sound_samples/phonemes/24.bin"

	.align 2
DirectSoundWaveData_Phoneme_25::
	.incbin "sound/direct_sound_samples/phonemes/25.bin"

	.align 2
DirectSoundWaveData_Phoneme_26::
	.incbin "sound/direct_sound_samples/phonemes/26.bin"

	.align 2
DirectSoundWaveData_Phoneme_27::
	.incbin "sound/direct_sound_samples/phonemes/27.bin"

	.align 2
DirectSoundWaveData_Phoneme_28::
	.incbin "sound/direct_sound_samples/phonemes/28.bin"

	.align 2
DirectSoundWaveData_Phoneme_29::
	.incbin "sound/direct_sound_samples/phonemes/29.bin"

	.align 2
DirectSoundWaveData_Phoneme_30::
	.incbin "sound/direct_sound_samples/phonemes/30.bin"

	.align 2
DirectSoundWaveData_Phoneme_31::
	.incbin "sound/direct_sound_samples/phonemes/31.bin"

	.align 2
DirectSoundWaveData_Phoneme_32::
	.incbin "sound/direct_sound_samples/phonemes/32.bin"

	.align 2
DirectSoundWaveData_Phoneme_33::
	.incbin "sound/direct_sound_samples/phonemes/33.bin"

	.align 2
DirectSoundWaveData_Phoneme_34::
	.incbin "sound/direct_sound_samples/phonemes/34.bin"

	.align 2
DirectSoundWaveData_Phoneme_35::
	.incbin "sound/direct_sound_samples/phonemes/35.bin"

	.align 2
DirectSoundWaveData_Phoneme_36::
	.incbin "sound/direct_sound_samples/phonemes/36.bin"

	.align 2
DirectSoundWaveData_Phoneme_37::
	.incbin "sound/direct_sound_samples/phonemes/37.bin"

	.align 2
DirectSoundWaveData_Phoneme_38::
	.incbin "sound/direct_sound_samples/phonemes/38.bin"

	.align 2
DirectSoundWaveData_Phoneme_39::
	.incbin "sound/direct_sound_samples/phonemes/39.bin"

	.align 2
DirectSoundWaveData_Phoneme_40::
	.incbin "sound/direct_sound_samples/phonemes/40.bin"

	.align 2
DirectSoundWaveData_Phoneme_41::
	.incbin "sound/direct_sound_samples/phonemes/41.bin"

	.align 2
DirectSoundWaveData_Phoneme_42::
	.incbin "sound/direct_sound_samples/phonemes/42.bin"

	.align 2
DirectSoundWaveData_Phoneme_43::
	.incbin "sound/direct_sound_samples/phonemes/43.bin"

	.align 2
DirectSoundWaveData_Phoneme_44::
	.incbin "sound/direct_sound_samples/phonemes/44.bin"

	.align 2
DirectSoundWaveData_Phoneme_45::
	.incbin "sound/direct_sound_samples/phonemes/45.bin"

	.align 2
DirectSoundWaveData_Phoneme_46::
	.incbin "sound/direct_sound_samples/phonemes/46.bin"

	.align 2
DirectSoundWaveData_Phoneme_47::
	.incbin "sound/direct_sound_samples/phonemes/47.bin"

	.align 2
DirectSoundWaveData_Phoneme_48::
	.incbin "sound/direct_sound_samples/phonemes/48.bin"

	.align 2
DirectSoundWaveData_Phoneme_49::
	.incbin "sound/direct_sound_samples/phonemes/49.bin"

	.align 2
DirectSoundWaveData_Phoneme_50::
	.incbin "sound/direct_sound_samples/phonemes/50.bin"

	.align 2
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/51.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
