gTrickHouse_Mechadoll_Zerimon::
	.string "ZERIMON$"

gTrickHouse_Mechadoll_Tinkermon::
	.string "TINKERMON$"

gTrickHouse_Mechadoll_Allomon_x::
	.string "ALLOMON_X$"

gTrickHouse_Mechadoll_Azurill::
	.string "AZURILL$"

gTrickHouse_Mechadoll_Zubamon::
	.string "ZUBAMON$"

gTrickHouse_Mechadoll_Angemon::
	.string "ANGEMON$"

gTrickHouse_Mechadoll_Zenimon::
	.string "ZENIMON$"

gTrickHouse_Mechadoll_Icebotamon::
	.string "ICEBOTAMON$"

gTrickHouse_Mechadoll_Nincada::
	.string "NINCADA$"

gTrickHouse_Mechadoll_Apemon::
	.string "APEMON$"

gTrickHouse_Mechadoll_Toyagumon::
	.string "TOYAGUMON$"

gTrickHouse_Mechadoll_Aurumon::
	.string "AURUMON$"

gTrickHouse_Mechadoll_Tinkermon2::
	.string "TINKERMON$"

gTrickHouse_Mechadoll_Aresdramon::
	.string "ARESDRAMON$"

gTrickHouse_Mechadoll_Toyagumon2::
	.string "TOYAGUMON$"

gTrickHouse_Mechadoll_Tinkermon3::
	.string "TINKERMON$"

gTrickHouse_Mechadoll_Icebotamon2::
	.string "ICEBOTAMON$"

gTrickHouse_Mechadoll_Carvanha::
	.string "CARVANHA$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "BURN HEAL$"

gTrickHouse_Mechadoll_HarborMail::
	.string "HARBOR MAIL$"

gTrickHouse_Mechadoll_SamePrice::
	.string "Same price$"

gTrickHouse_Mechadoll_60Yen::
	.string "¥60$"

gTrickHouse_Mechadoll_55Yen::
	.string "¥55$"

gTrickHouse_Mechadoll_Nothing::
	.string "Nothing$"

gTrickHouse_Mechadoll_CostMore::
	.string "They will cost more.$"

gTrickHouse_Mechadoll_CostLess::
	.string "They will cost less.$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "Same price$"

gTrickHouse_Mechadoll_Male::
	.string "Male$"

gTrickHouse_Mechadoll_Female::
	.string "Female$"

gTrickHouse_Mechadoll_Neither::
	.string "Neither$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "Elderly men$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "Elderly ladies$"

gTrickHouse_Mechadoll_SameNumber::
	.string "Same number$"

gTrickHouse_Mechadoll_None::
	.string "None$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Two2::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Four::
	.string "4$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Eight::
	.string "8$"

gTrickHouse_Mechadoll_Six2::
	.string "6$"

gTrickHouse_Mechadoll_Seven2::
	.string "7$"

gTrickHouse_Mechadoll_Eight2::
	.string "8$"
